### ISSUE TITLE
Wide screen render issue

### ISSUE THREAD

**Issue by littlejon** [varigence/docs#43]
This line is causing width rendering issues for your help guide docs on screens with a pixel width less than 1648px. Setting back to 1170px fixes the rendering issue. To fit content to screen you could switch to `.container-fluid` rather than `.container`

https://github.com/varigence/docs/blob/8b37cc61040c28bc6701ac202a03248e72d7c6eb/docfx/templates/varigence-template-html/styles/docfx.vendor.css#L425

**Comment by RoelantVos** [comment]
Apologies for the late response to this, but I think this has been fixed but the issue wasn't closed. If still an issue, please create a new one.
